import { Timestamp } from "firebase/firestore";

// ═══════════════════════════════════════════════════════════════
// PRODUCT REQUEST - Richieste prodotti pulizia dall'operatore
// ═══════════════════════════════════════════════════════════════

export type ProductRequestStatus = "pending" | "fulfilled" | "cancelled";

export interface ProductRequestItem {
  itemId: string;
  name: string;
  quantity: number;
  categoryId?: string;
}

export interface ProductRequest {
  id: string;
  
  // Riferimenti
  propertyId: string;
  propertyName: string;
  propertyAddress?: string;
  cleaningId: string;           // Pulizia in cui è stata fatta la richiesta
  
  // Chi ha richiesto
  requestedBy: string;          // operatorId
  requestedByName: string;
  
  // Prodotti richiesti
  items: ProductRequestItem[];
  
  // Note opzionali
  notes?: string;
  
  // Stato
  status: ProductRequestStatus;
  
  // Tracking
  createdAt: Timestamp;
  updatedAt: Timestamp;
  
  // Se evasa
  fulfilledAt?: Timestamp;
  fulfilledInOrderId?: string;  // ID dell'ordine che ha evaso la richiesta
  fulfilledInCleaningId?: string; // ID della pulizia successiva
}

// ═══════════════════════════════════════════════════════════════
// INPUT TYPES
// ═══════════════════════════════════════════════════════════════

export interface CreateProductRequestInput {
  propertyId: string;
  propertyName: string;
  propertyAddress?: string;
  cleaningId: string;
  items: ProductRequestItem[];
  notes?: string;
}

// ═══════════════════════════════════════════════════════════════
// ORDER TYPES EXTENDED - Per ordini con prodotti pulizia
// ═══════════════════════════════════════════════════════════════

export type OrderItemType = "linen" | "cleaning_product";

export interface OrderItemExtended {
  id: string;
  itemId: string;
  name: string;
  quantity: number;
  type: OrderItemType;        // "linen" per biancheria, "cleaning_product" per prodotti pulizia
  categoryId?: string;
}

// Struttura ordine estesa con supporto prodotti pulizia
export interface OrderExtended {
  id: string;
  propertyId: string;
  propertyName: string;
  propertyAddress?: string;
  propertyCity?: string;
  propertyPostalCode?: string;
  propertyFloor?: string;
  propertyApartment?: string;
  
  riderId?: string;
  riderName?: string;
  
  status: string;
  type: "LINEN" | "PRODUCTS" | "MIXED";  // Tipo ordine
  
  // Items separati per tipo
  linenItems: OrderItemExtended[];       // Articoli biancheria
  cleaningProducts: OrderItemExtended[]; // Prodotti pulizia
  
  // Legacy support - tutti gli items insieme
  items: OrderItemExtended[];
  
  // Riferimenti
  cleaningId?: string;
  productRequestIds?: string[];  // ID delle richieste prodotti evase
  
  scheduledDate: any;
  notes?: string;
  
  autoGenerated: boolean;
  createdAt: any;
  updatedAt: any;
  deliveredAt?: any;
}
